### ISSUE TITLE
Waybar doesn't appear on display

### ISSUE THREAD

**Issue by KeksNino** [Pahasara/dotFiles#1]
im trying to start waybar but it doesnt open with both themes.
[log.txt](https://github.com/user-attachments/files/16822115/log.txt)

**Comment by Pahasara** [comment]
Did u modified the monitor name in **_/home/user/.config/waybar/config_**. If u use hyprland u can get the monior name by using _**hyprctl monitors all**_. Seems like a output misconfiguration in **_config_**. Give me the update..

**Comment by KeksNino** [comment]
it was a different problem but i managed to fix it
